[colors.primary]
background = '#040811'
foreground = '#ffffff'

[colors.normal]
black=   '#474747'
red = '#fc5555'
green = '#5be599'
yellow = '#fcfc14'
blue = '#0000ff'
magenta = '#fc14ec'
cyan = '#14f4fc'
white = '#ffffff'

[colors.bright]
black = '#474747'
red = '#fc5555'
green = '#5be599'
yellow = '#fcfc71'
blue = '#0000ff'
magenta = '#fc14ec'
cyan = '#14f4fc'
white = '#ffffff'

[window]
opacity = 0.85
