require("modules.events")
require("modules.monitors")
require("modules.ui")
require("modules.layout")
require("modules.keybinds")
require("modules.animation")
require("modules.input")
require("modules.rules")
