theme = "my_default"

[keybinds]
next = "alt j"
previous = "alt k"

[placeholders]
"default" = { input = "Search applications", list = "No Results" }

[providers]
default = [
    "desktopapplications",
    "calc",
]
empty = [ "desktopapplications" ]
