
[colors]
background = '#011423'
foreground = '#cbe0f0'
cursor_bg = '#ffffff'
cursor_fg = '#011423'
cursor_border = '#ffffff'
selection_bg = '#033259'
selection_fg = '#CBE0F0'
split = '#214969'

ansi = [
    '#214969',
    '#E52E2E',
    '#44FFB1',
    '#FFE073',
    '#0FC5ED',
    '#a277ff',
    '#24EAF7',
    '#CBE0F0',
]

brights = [
    '#214969',
    '#E52E2E',
    '#44FFB1',
    '#FFE073',
    '#0FC5ED',
    '#a277ff',
    '#24EAF7',
    '#CBE0F0',
]

[colors.tab_bar]
background = "#2d2d2d"

[colors.tab_bar.active_tab]
bg_color = '#011423'
fg_color = '#ffffff'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#2d2d2d'
fg_color = '#ffffff'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#2d2d2d'
fg_color = '#ffffff'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'


[metadata]
name = 'Emarald Glow'
