import = [
    "~/.config/alacritty/colors/m2x07-dark.toml"
]

[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
blinking = "On"

[font]
size = 7.5

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.8
dynamic_title = false
title = "Alacritty"
dimensions = {columns = 115, lines = 30}

