import = [
    "~/.config/alacritty/colors/m2x07-dark.toml"
    # "~/.config/alacritty/colors/catppuccin-macchiato.toml"
    # "~/.config/alacritty/colors/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
blinking = "On"

[font]
size = 10
offset = {x = 0, y = 0}

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "SemiBold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"

[scrolling]
multiplier = 3
history = 10000

[window]
# padding = {x = 5, y = 0 }
opacity = 1
title = "Alacritty"
decorations = "None"
dynamic_title = true
dimensions = {columns = 115, lines = 30}

