
[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 450
blink_timeout = 0

[font]
size = 11.5
offset = {x = 0, y = 0}

[font.bold]
family = "Maple Mono NL NF CN"
style = "Bold"

[font.bold_italic]
family = "Maple Mono NL NF CN"
style = "SemiBold Italic"

[font.italic]
family = "Maple Mono NL NF CN"
style = "Italic"

[font.normal]
family = "Maple Mono NL NF CN"
style = "Regular"

[scrolling]
multiplier = 3
history = 10000

[window]
# padding = {x = 5, y = 0 }
title = "Alacritty"
decorations = "Full"
dynamic_title = true
dimensions = {columns = 115, lines = 30}

[general]
import = [
    # "~/.config/alacritty/colors/emarald-glow.toml"
    "~/.config/alacritty/colors/noir.toml"
    # "~/.config/alacritty/colors/catppuccin-macchiato.toml"
    # "~/.config/alacritty/colors/catppuccin-mocha.toml"
]

