
[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
blinking = "On"

[font]
size = 10
offset = {x = 0, y = 0}

[font.bold]
family = "JetBrainsMonoNL Nerd Font "
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font "
style = "SemiBold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font "
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font "
style = "Regular"

[scrolling]
multiplier = 3
history = 10000

[window]
# padding = {x = 5, y = 0 }
title = "Alacritty"
decorations = "Full"
dynamic_title = true
dimensions = {columns = 115, lines = 30}

[general]
import = [
    # "~/.config/alacritty/colors/m2x07-emarald-glow.toml"
    "~/.config/alacritty/colors/m2x07-noir.toml"
    # "~/.config/alacritty/colors/catppuccin-macchiato.toml"
    # "~/.config/alacritty/colors/catppuccin-mocha.toml"
]

