
[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 450
blink_timeout = 0

[font]
size = 11.5
offset = {x = 0, y = 0}

[font.normal]
family = "Maple Mono NF CN"
style = "Regular"

[font.bold]
family = "Maple Mono NF CN"
style = "Bold"

[font.italic]
family = "Maple Mono NF CN"
style = "Italic"

[font.bold_italic]
family = "Maple Mono NF CN"
style = "SemiBold Italic"

[scrolling]
multiplier = 3
history = 10000

[window]
padding = { x = 10, y = 10 }
title = "Alacritty"
decorations = "full"
dynamic_title = true
dimensions = { columns = 115, lines = 30 }

[general]
import = [
    # "~/.config/alacritty/colors/emarald-glow.toml"
    "~/.config/alacritty/colors/noir.toml"
    # "~/.config/alacritty/colors/noir-soft.toml"
    # "~/.config/alacritty/colors/tokyonight_night.toml"
    # "~/.config/alacritty/colors/catppuccin-mocha.toml"
]

