import = [
    "~/.config/alacritty/colors/m2x07-dark.toml"
]

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
blinking = "On"

[font]
size = 7.5
offset = {x = 0, y = 1}

[font.bold]
family = "GeistMono Nerd Font"
style = "SemiBold"

[font.bold_italic]
family = "GeistMono Nerd Font"
style = "SemiBold Italic"

[font.italic]
family = "GeistMono Nerd Font"
style = "Italic"

[font.normal]
family = "GeistMono Nerd Font"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 1
dynamic_title = false
title = "Alacritty"
dimensions = {columns = 115, lines = 30}

